version: '3'

services:
  boinc:
    container_name: boinc
    restart: always
    volumes:
      - boinc:/var/lib/boinc
    image: ichikawayukko/boinc
    hostname: YOUR-HOSTNAME_HERE   # This will be registered for identify each boinc host

volumes:
  boinc:
